### ISSUE TITLE
File not found when using prefixes with static files directories

### ISSUE THREAD

**Issue by kdb13** [coderedcorp/django-sass#14]
When we prefix one of the directory in `STATICFILES_DIRS` and then write the full relative path (along with prefix) in the import statement, the `sass` compiler is not able to find the file.

## Case 1: without prefix
Suppose, we have the following static directory path.
```
STATICFILES_DIRS = [
    BASE_DIR / "shoppr/static",
]
```

Now, when we import a file from there like `@import "scss/bootstrap/bootstrap";` it works perfectly.

## Case 2: with prefix
Now, we have the same directory path, but with a prefix for namespacing.
```
STATICFILES_DIRS = [
    ("shoppr", BASE_DIR / "shoppr/static"),
]
```

Now, when we try to import this `@import "shoppr/scss/bootstrap/bootstrap;" it throws an error:
```
sass.CompileError: Error: File to import not found or unreadable: shoppr/scss/bootstrap/bootstrap.
        on line 3:1 of catalog/static/catalog/scss/styles.scss
>> @import "shoppr/scss/bootstrap/bootstrap";
```

**Comment by vsalvino** [comment]
Interesting use-case. Thanks for reporting.

For the time being, I would recommend the Django best practice of using apps, and naming the static file folders the same as your app. This way you will not need prefixes and there will never be collisions (especially with `collectstatic` too).

File structure:

```
project/
|- shoppr/
   |- static/
      |- shoppr/
         |- scss/
```

With this file structure you will be able to use `@import "shoppr/scss/bootstrap/bootstrap";` in your sass.

---

More info on the bug: `find_static_paths` is how we find all of the available physical filesystem paths, and pass those through to the sass compiler. Since the prefix means it is no longer a real filesystem path, we may need to find a workaround on how to translate that prefixed path into a real path before passing that into the sass compiler.

https://github.com/coderedcorp/django-sass/blob/16fbb498ae4cd9cbcc00a07be3e27d4c9080c161/django_sass/__init__.py#L8-L22

**Comment by kdb13** [comment]
@vsalvino Great! I didn't think of that. I'll use app-named folders for global static files as well.

Actually, `shoppr` is the name for my project and I am storing shared static files there. I'll just create a **shoppr** folder inside the `static` directory.

Thank you so much.
